//go:build !ignore_autogenerated

/*
** Copyright (c) 2024 Oracle and/or its affiliates.
**
** The Universal Permissive License (UPL), Version 1.0
**
** Subject to the condition set forth below, permission is hereby granted to any
** person obtaining a copy of this software, associated documentation and/or data
** (collectively the "Software"), free of charge and under any and all copyright
** rights in the Software, and any and all patent rights owned or freely
** licensable by each licensor hereunder covering either (i) the unmodified
** Software as contributed to or provided by such licensor, or (ii) the Larger
** Works (as defined below), to deal in both
**
** (a) the Software, and
** (b) any piece of software and/or hardware listed in the lrgrwrks.txt file if
** one is included with the Software (each a "Larger Work" to which the Software
** is contributed by such licensors),
**
** without restriction, including without limitation the rights to copy, create
** derivative works of, display, perform, and distribute the Software and make,
** use, sell, offer for sale, import, export, have made, and have sold the
** Software and the Larger Work(s), and to sublicense the foregoing rights on
** either these or other terms.
**
** This license is subject to the following condition:
** The above copyright notice and either this complete permission notice or at
** a minimum a reference to the UPL must be included in all copies or
** substantial portions of the Software.
**
** THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
** IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
** FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
** AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
** LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
** OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
** SOFTWARE.
 */

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
	timex "time"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateSecret) DeepCopyInto(out *CertificateSecret) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateSecret.
func (in *CertificateSecret) DeepCopy() *CertificateSecret {
	if in == nil {
		return nil
	}
	out := new(CertificateSecret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DBWalletSecret) DeepCopyInto(out *DBWalletSecret) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DBWalletSecret.
func (in *DBWalletSecret) DeepCopy() *DBWalletSecret {
	if in == nil {
		return nil
	}
	out := new(DBWalletSecret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlobalSettings) DeepCopyInto(out *GlobalSettings) {
	*out = *in
	if in.CacheMetadataGraphQLExpireAfterAccess != nil {
		in, out := &in.CacheMetadataGraphQLExpireAfterAccess, &out.CacheMetadataGraphQLExpireAfterAccess
		*out = new(timex.Duration)
		**out = **in
	}
	if in.CacheMetadataJWKSEnabled != nil {
		in, out := &in.CacheMetadataJWKSEnabled, &out.CacheMetadataJWKSEnabled
		*out = new(bool)
		**out = **in
	}
	if in.CacheMetadataJWKSInitialCapacity != nil {
		in, out := &in.CacheMetadataJWKSInitialCapacity, &out.CacheMetadataJWKSInitialCapacity
		*out = new(int32)
		**out = **in
	}
	if in.CacheMetadataJWKSMaximumSize != nil {
		in, out := &in.CacheMetadataJWKSMaximumSize, &out.CacheMetadataJWKSMaximumSize
		*out = new(int32)
		**out = **in
	}
	if in.CacheMetadataJWKSExpireAfterAccess != nil {
		in, out := &in.CacheMetadataJWKSExpireAfterAccess, &out.CacheMetadataJWKSExpireAfterAccess
		*out = new(timex.Duration)
		**out = **in
	}
	if in.CacheMetadataJWKSExpireAfterWrite != nil {
		in, out := &in.CacheMetadataJWKSExpireAfterWrite, &out.CacheMetadataJWKSExpireAfterWrite
		*out = new(timex.Duration)
		**out = **in
	}
	if in.DatabaseAPIManagementServicesDisabled != nil {
		in, out := &in.DatabaseAPIManagementServicesDisabled, &out.DatabaseAPIManagementServicesDisabled
		*out = new(bool)
		**out = **in
	}
	if in.DBInvalidPoolTimeout != nil {
		in, out := &in.DBInvalidPoolTimeout, &out.DBInvalidPoolTimeout
		*out = new(timex.Duration)
		**out = **in
	}
	if in.FeatureGraphQLMaxNestingDepth != nil {
		in, out := &in.FeatureGraphQLMaxNestingDepth, &out.FeatureGraphQLMaxNestingDepth
		*out = new(int32)
		**out = **in
	}
	if in.SecurityCredentialsAttempts != nil {
		in, out := &in.SecurityCredentialsAttempts, &out.SecurityCredentialsAttempts
		*out = new(int32)
		**out = **in
	}
	if in.SecurityCredentialsLockTime != nil {
		in, out := &in.SecurityCredentialsLockTime, &out.SecurityCredentialsLockTime
		*out = new(timex.Duration)
		**out = **in
	}
	if in.StandaloneHTTPPort != nil {
		in, out := &in.StandaloneHTTPPort, &out.StandaloneHTTPPort
		*out = new(int32)
		**out = **in
	}
	if in.StandaloneHttpsPort != nil {
		in, out := &in.StandaloneHttpsPort, &out.StandaloneHttpsPort
		*out = new(int32)
		**out = **in
	}
	if in.StandaloneStopTimeout != nil {
		in, out := &in.StandaloneStopTimeout, &out.StandaloneStopTimeout
		*out = new(timex.Duration)
		**out = **in
	}
	if in.CacheMetadataTimeout != nil {
		in, out := &in.CacheMetadataTimeout, &out.CacheMetadataTimeout
		*out = new(timex.Duration)
		**out = **in
	}
	if in.CacheMetadataEnabled != nil {
		in, out := &in.CacheMetadataEnabled, &out.CacheMetadataEnabled
		*out = new(bool)
		**out = **in
	}
	if in.DatabaseAPIEnabled != nil {
		in, out := &in.DatabaseAPIEnabled, &out.DatabaseAPIEnabled
		*out = new(bool)
		**out = **in
	}
	if in.DebugPrintDebugToScreen != nil {
		in, out := &in.DebugPrintDebugToScreen, &out.DebugPrintDebugToScreen
		*out = new(bool)
		**out = **in
	}
	if in.ICAPPort != nil {
		in, out := &in.ICAPPort, &out.ICAPPort
		*out = new(int32)
		**out = **in
	}
	if in.ICAPSecurePort != nil {
		in, out := &in.ICAPSecurePort, &out.ICAPSecurePort
		*out = new(int32)
		**out = **in
	}
	if in.LogProcedure != nil {
		in, out := &in.LogProcedure, &out.LogProcedure
		*out = new(bool)
		**out = **in
	}
	if in.SecurityDisableDefaultExclusionList != nil {
		in, out := &in.SecurityDisableDefaultExclusionList, &out.SecurityDisableDefaultExclusionList
		*out = new(bool)
		**out = **in
	}
	if in.SecurityMaxEntries != nil {
		in, out := &in.SecurityMaxEntries, &out.SecurityMaxEntries
		*out = new(int32)
		**out = **in
	}
	if in.SecurityVerifySSL != nil {
		in, out := &in.SecurityVerifySSL, &out.SecurityVerifySSL
		*out = new(bool)
		**out = **in
	}
	if in.CertSecret != nil {
		in, out := &in.CertSecret, &out.CertSecret
		*out = new(CertificateSecret)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlobalSettings.
func (in *GlobalSettings) DeepCopy() *GlobalSettings {
	if in == nil {
		return nil
	}
	out := new(GlobalSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PasswordSecret) DeepCopyInto(out *PasswordSecret) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PasswordSecret.
func (in *PasswordSecret) DeepCopy() *PasswordSecret {
	if in == nil {
		return nil
	}
	out := new(PasswordSecret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PoolSettings) DeepCopyInto(out *PoolSettings) {
	*out = *in
	out.DBSecret = in.DBSecret
	out.DBAdminUserSecret = in.DBAdminUserSecret
	out.DBCDBAdminUserSecret = in.DBCDBAdminUserSecret
	if in.DBPoolDestroyTimeout != nil {
		in, out := &in.DBPoolDestroyTimeout, &out.DBPoolDestroyTimeout
		*out = new(timex.Duration)
		**out = **in
	}
	if in.DebugTrackResources != nil {
		in, out := &in.DebugTrackResources, &out.DebugTrackResources
		*out = new(bool)
		**out = **in
	}
	if in.FeatureOpenservicebrokerExclude != nil {
		in, out := &in.FeatureOpenservicebrokerExclude, &out.FeatureOpenservicebrokerExclude
		*out = new(bool)
		**out = **in
	}
	if in.FeatureSDW != nil {
		in, out := &in.FeatureSDW, &out.FeatureSDW
		*out = new(bool)
		**out = **in
	}
	if in.OwaTraceSql != nil {
		in, out := &in.OwaTraceSql, &out.OwaTraceSql
		*out = new(bool)
		**out = **in
	}
	if in.SecurityJWTProfileEnabled != nil {
		in, out := &in.SecurityJWTProfileEnabled, &out.SecurityJWTProfileEnabled
		*out = new(bool)
		**out = **in
	}
	if in.SecurityJWKSSize != nil {
		in, out := &in.SecurityJWKSSize, &out.SecurityJWKSSize
		*out = new(int32)
		**out = **in
	}
	if in.SecurityJWKSConnectionTimeout != nil {
		in, out := &in.SecurityJWKSConnectionTimeout, &out.SecurityJWKSConnectionTimeout
		*out = new(timex.Duration)
		**out = **in
	}
	if in.SecurityJWKSReadTimeout != nil {
		in, out := &in.SecurityJWKSReadTimeout, &out.SecurityJWKSReadTimeout
		*out = new(timex.Duration)
		**out = **in
	}
	if in.SecurityJWKSRefreshInterval != nil {
		in, out := &in.SecurityJWKSRefreshInterval, &out.SecurityJWKSRefreshInterval
		*out = new(timex.Duration)
		**out = **in
	}
	if in.SecurityJWTAllowedSkew != nil {
		in, out := &in.SecurityJWTAllowedSkew, &out.SecurityJWTAllowedSkew
		*out = new(timex.Duration)
		**out = **in
	}
	if in.SecurityJWTAllowedAge != nil {
		in, out := &in.SecurityJWTAllowedAge, &out.SecurityJWTAllowedAge
		*out = new(timex.Duration)
		**out = **in
	}
	if in.DBPort != nil {
		in, out := &in.DBPort, &out.DBPort
		*out = new(int32)
		**out = **in
	}
	if in.JDBCInactivityTimeout != nil {
		in, out := &in.JDBCInactivityTimeout, &out.JDBCInactivityTimeout
		*out = new(int32)
		**out = **in
	}
	if in.JDBCInitialLimit != nil {
		in, out := &in.JDBCInitialLimit, &out.JDBCInitialLimit
		*out = new(int32)
		**out = **in
	}
	if in.JDBCMaxConnectionReuseCount != nil {
		in, out := &in.JDBCMaxConnectionReuseCount, &out.JDBCMaxConnectionReuseCount
		*out = new(int32)
		**out = **in
	}
	if in.JDBCMaxLimit != nil {
		in, out := &in.JDBCMaxLimit, &out.JDBCMaxLimit
		*out = new(int32)
		**out = **in
	}
	if in.JDBCAuthEnabled != nil {
		in, out := &in.JDBCAuthEnabled, &out.JDBCAuthEnabled
		*out = new(bool)
		**out = **in
	}
	if in.JDBCMaxStatementsLimit != nil {
		in, out := &in.JDBCMaxStatementsLimit, &out.JDBCMaxStatementsLimit
		*out = new(int32)
		**out = **in
	}
	if in.JDBCMinLimit != nil {
		in, out := &in.JDBCMinLimit, &out.JDBCMinLimit
		*out = new(int32)
		**out = **in
	}
	if in.JDBCStatementTimeout != nil {
		in, out := &in.JDBCStatementTimeout, &out.JDBCStatementTimeout
		*out = new(int32)
		**out = **in
	}
	if in.MiscPaginationMaxRows != nil {
		in, out := &in.MiscPaginationMaxRows, &out.MiscPaginationMaxRows
		*out = new(int32)
		**out = **in
	}
	if in.RestEnabledSqlActive != nil {
		in, out := &in.RestEnabledSqlActive, &out.RestEnabledSqlActive
		*out = new(bool)
		**out = **in
	}
	if in.DBWalletSecret != nil {
		in, out := &in.DBWalletSecret, &out.DBWalletSecret
		*out = new(DBWalletSecret)
		**out = **in
	}
	if in.TNSAdminSecret != nil {
		in, out := &in.TNSAdminSecret, &out.TNSAdminSecret
		*out = new(TNSAdminSecret)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PoolSettings.
func (in *PoolSettings) DeepCopy() *PoolSettings {
	if in == nil {
		return nil
	}
	out := new(PoolSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestDataServices) DeepCopyInto(out *RestDataServices) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestDataServices.
func (in *RestDataServices) DeepCopy() *RestDataServices {
	if in == nil {
		return nil
	}
	out := new(RestDataServices)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RestDataServices) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestDataServicesList) DeepCopyInto(out *RestDataServicesList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RestDataServices, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestDataServicesList.
func (in *RestDataServicesList) DeepCopy() *RestDataServicesList {
	if in == nil {
		return nil
	}
	out := new(RestDataServicesList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RestDataServicesList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestDataServicesSpec) DeepCopyInto(out *RestDataServicesSpec) {
	*out = *in
	in.GlobalSettings.DeepCopyInto(&out.GlobalSettings)
	if in.PoolSettings != nil {
		in, out := &in.PoolSettings, &out.PoolSettings
		*out = make([]*PoolSettings, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(PoolSettings)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestDataServicesSpec.
func (in *RestDataServicesSpec) DeepCopy() *RestDataServicesSpec {
	if in == nil {
		return nil
	}
	out := new(RestDataServicesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestDataServicesStatus) DeepCopyInto(out *RestDataServicesStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestDataServicesStatus.
func (in *RestDataServicesStatus) DeepCopy() *RestDataServicesStatus {
	if in == nil {
		return nil
	}
	out := new(RestDataServicesStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TNSAdminSecret) DeepCopyInto(out *TNSAdminSecret) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TNSAdminSecret.
func (in *TNSAdminSecret) DeepCopy() *TNSAdminSecret {
	if in == nil {
		return nil
	}
	out := new(TNSAdminSecret)
	in.DeepCopyInto(out)
	return out
}
