apiVersion: database.oracle.com/v1
kind: RestDataServices
metadata:
  name: ords-sample-2
spec:
  replicas: 3
  workloadType: Deployment
  image: container-registry.oracle.com/database/ords:23.4.0
  forceRestart: false
  globalSettings:
    standalone.http.port: 8083
  poolSettings:
    - poolName: Pool1
      dbUsername: ORDS_PUBLIC_USER
      dbSecret:
        secretName:  db-auth
        passwordKey: password
    - poolName: Pool2
      dbUsername: ORDS_PUBLIC_USER
      dbSecret:
        secretName:  db-auth
        passwordKey: password
      jdbcMaxLimit: 201