apiVersion: database.oracle.com/v1
kind: RestDataServices
metadata:
  labels:
    app.kubernetes.io/name: restdataservices
    app.kubernetes.io/instance: restdataservices-sample
    app.kubernetes.io/part-of: oracle-ords-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: oracle-ords-operator
  name: restdataservices-sample-2
spec:
  replicas: 2
  image: container-registry.oracle.com/database/ords:latest
  globalSettings:
    standaloneHttpPort: 8081

