apiVersion: database.oracle.com/v1
kind: RestDataServices
metadata:
  labels:
    app.kubernetes.io/name: ords
    app.kubernetes.io/instance: ords-sample
    app.kubernetes.io/part-of: oracle-ords-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: oracle-ords-operator
  name: ords-sample-1
spec:
  replicas: 1
  workloadType: DaemonSet
  image: container-registry.oracle.com/database/ords:23.4.0
  globalSettings:
    standaloneBinds: 0.0.0.0
    standaloneHttpPort: 8082
  poolSettings:
    - poolName: Pool1
      dbUsername: ORDS_PUBLIC_USER
      dbSecret:
        secretName:  db-auth
        passwordKey: password
    - poolName: Pool2
      dbUsername: ORDS_PUBLIC_USER
      dbSecret:
        secretName:  db-auth
        passwordKey: password
      jdbcMaxLimit: 200