name: Build Release
on:
  release:
    types: [published]

env:
  REGISTRY: ghcr.io
  MANIFEST: ${GITHUB_REPOSITORY#${GITHUB_REPOSITORY_OWNER}/}.yaml
  VERSION: ${GITHUB_REF_NAME:1}
  
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write

    steps:
      - name: Output Environment
        run: |
          echo "Manifest: ${{ env.MANIFEST }}"
          echo "Image: ${{ github.repository }}:${{ env.VERSION }}"
      
      - name: Validate Tag Name
        run: |
          if [[ ! $GITHUB_REF_NAME =~ ^v[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
            echo "Invalid tag name format. Must be in the format vMAJOR.MINOR.PATCH"
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and Push Manifest
        run: | 
          make release-manifest IMG=${{ github.repository }}:${{ env.VERSION }}
          gh release upload ${{github.event.release.tag_name}} ${{ env.MANIFEST }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        
      # Set up BuildKit Docker container builder to be able to build
      # multi-platform images and export cache
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
