name: Build Release
on:
  push:
    tags:
      - '*'

env:
  REGISTRY: ghcr.io
  MANIFEST: ${GITHUB_REPOSITORY#${GITHUB_REPOSITORY_OWNER}/}.yml
  VERSION: ${GITHUB_REF_NAME:1}
  
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Output Environment
        run: |
          echo "Manifest: ${{ env.MANIFEST }}"
          echo "Image: ${{ github.repository }}:${{ env.VERSION }}"
      
      - name: Validate Tag Name
        run: |
          if [[ ! $GITHUB_REF_NAME =~ ^v[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
            echo "Invalid tag name format. Must be in the format vMAJOR.MINOR.PATCH"
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build manifest
        run: make release-manifest IMG=${{ github.repository }}:${{ env.VERSION }}

      # Get the release ID or URL
      - name: Get Release ID
        id: get_release
        run: |
          echo "release_id=$(curl -s -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' https://api.github.com/repos/${{ github.repository }}/releases/tags/$GITHUB_REF_NAME | jq -r '.id')" >> $GITHUB_ENV

      # Upload the artifact to the release
      - name: Upload Artifact to Release
        run: |
          echo "Uploading ${{ env.MANIFEST }} to Release ID: ${{ env.release_id }}"
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/octet-stream" \
            --data-binary @${{ env.MANIFEST }} \
            "https://uploads.github.com/repos/${{ github.repository }}/releases/${{ env.release_id }}/assets?name=${{ env.MANIFEST }}"

      # Set up BuildKit Docker container builder to be able to build
      # multi-platform images and export cache
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
