name: Validate Push

on:
  pull_request:
    branches:
      - '*'  # Run on all branches

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Run 'make generate manifests'
        run: make generate manifests

      - name: Generate documentation
        run: docker run -u $(id -u):$(id -g) --rm -v ${PWD}:/workdir ghcr.io/fybrik/crdoc:latest --resources /workdir/config/crd/bases --output /workdir/docs/api.md

      - name: Check for changes
        run: |
          git diff --exit-code
          if [ $? -ne 0 ]; then
            echo "Changes detected after generation. Rejecting push."
            exit 1
          fi