name: Validate Push

on:
  pull_request:
    branches:
      - '*'  # Run on all branches

jobs:
  document:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/fybrik/crdoc:latest
      volumes:
        - ${{ github.workspace }}:/workdir
      options: --entrypoint sh

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate API Documentation
        run: crdoc --resources /workdir/config/crd/bases --output /workdir/docs/api.md

  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Run 'make generate manifests'
        run: make generate manifests

      - name: Check for changes
        run: |
          git diff --exit-code
          if [ $? -ne 0 ]; then
            echo "Changes detected after generation. Rejecting push."
            exit 1
          fi