# This workflow will validate that manifests have been generated properly on push
name: Validate Push

on:
  push:
    branches:
      - '*' 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Run 'make generate manifests'
      run: make generate manifests

    - name: Check for changes
      run: |
        git diff --exit-code
        if [ $? -ne 0 ]; then
          echo "Changes detected after generation. Rejecting push."
          exit 1
        fi
